### ISSUE TITLE
revisit gdal nodata handling / finally add color to alpha support?

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2023]
This is a followup to 46b16c9 / #1161 mainly because #727 and #1018 are not fully solved (for rgb(a) images).

We currently support:
- [x] Automatically detecting nodata values and setting them to transparent for `gray` images,  `rgb` images, and  `paletted/colormapped` (#1160) images ( though alpha is used instead of `nodata` for rgba images).
- [x] Allowing the user to supply `nodata` option in layer options to override the existing `nodata` value, or set one if none exists (#1161), for grayscale data ONLY.

Further needs:
- [x] - unsigned/float matching issues
- [x] - since user supplied nodata only works for grayscale data we still need a way for user supplied color to alpha for rgb(a) images like mentioned in #1018 but not solved.
- [ ] - potential confusion over nodata per band vs at dataset level? http://trac.osgeo.org/gdal/ticket/2734 | http://trac.osgeo.org/gdal/wiki/rfc15_nodatabitmask
- [ ] - create some variable test cases with `gdalsetnull.py`: http://gis.stackexchange.com/a/2929/15440:
  - nodata detection in data when data also has an alpha channel - does this occur/matter?
  - figure out if we should handle rgb(a) images with different nodata values per band.
