### ISSUE TITLE
Revisit precision of glyph widths

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2201]
Mapnik 2.3.x and all previous versions have rounded to an integer when calculating the pixel space between glyphs.

In Mapnik 2.3.x this is currently done here: https://github.com/mapnik/mapnik/blob/ce1ff9902eca96f1384c631442dfb9f4e988b2ab/src/font_engine_freetype.cpp#L347

```
 unsigned tempx = face->glyph->advance.x >> 6;
```

This should likely instead be a floating point, but this needs more research.
### background

As part of the large effort to merge the harfbuzz branch into master that landed in https://github.com/mapnik/mapnik/commit/64d5153aeaeb1c9e736bfead297dfea39b066d2c I needed to review hundreds of failing visual testcases (`python tests/visual_tests/test.py`) to assess which where new bugs vs which were improvements and demanded updated to expected images.

In order to help reduce the number of failing tests I commented [this line](https://github.com/mapnik/mapnik/blob/e618a654985194a95f7cf9c8d48f82e2d1062057/include/mapnik/text/harfbuzz_shaper.hpp#L108) and replaced with [this line](https://github.com/mapnik/mapnik/blob/e618a654985194a95f7cf9c8d48f82e2d1062057/include/mapnik/text/harfbuzz_shaper.hpp#L109) which I found seemed to restore glyph widths to Mapnik 2.3.x behavior and avoided many failing tests. I also did this [here](https://github.com/mapnik/mapnik/blob/e618a654985194a95f7cf9c8d48f82e2d1062057/src/text/face.cpp#L91-L94) but can't recall which was needed or if both were.
### Tasks ahead

Now that harfbuzz is merged into master we need to:
- [x] - Assess if moving back to `/64.0` improves the visual quality of text rendering and if so;
- [x] - Updated all the expected test images in master (`python tests/visual_tests/test.py -q --overwrite`)
- [x] - Assess any impacts switching from a int to double may or may not have on glyph caching
- [x]  - Assess where exactly the `/64.0` change needs to be made, [here](https://github.com/mapnik/mapnik/blob/e618a654985194a95f7cf9c8d48f82e2d1062057/src/text/face.cpp#L91-L94) or [here](https://github.com/mapnik/mapnik/blob/e618a654985194a95f7cf9c8d48f82e2d1062057/include/mapnik/text/harfbuzz_shaper.hpp#L108-L109) or both, and why are their two places this is done?
- [x]  - Assess any performance impacts of this change by running [this benchmark](https://github.com/mapnik/mapnik/blob/e618a654985194a95f7cf9c8d48f82e2d1062057/benchmark/run#L24-L31) before and after the change.
