### ISSUE TITLE
Full expressions support

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2224]
The `expr-v2` branch is merged meaning in Mapnik master (3.x) all styling properties are expression types and therefore can be data-driven. But there is still work to do to get things stable. This ticket stands to track tasks:
- [x]  Profiling / performance focus on shaping: need to speed up harfbuzz by either caching shaped results or smarter code shortcuts - https://github.com/mapnik/mapnik/issues/2326
- [x] Expressions support for enumerations
- [x]  Profiling / performance focus on load_map: the two step / fallback to detect possible expressions is sub-optimal: a smarter approach is needed.
- [x] Expressions support for `stroke-dasharray`: https://github.com/mapnik/mapnik/issues/2168
- [x] Flip `clip` defaults to false
- [x] Review to ensure no loss of code in merges - e.g. did `scale_factor` addition to transforms in 2.3.x branch make it through to master?
- [x] Review expected visual tests between agg and cairo - any obvious bugs needing addressed? https://github.com/mapnik/mapnik/issues/2325
- [x]  Ensure rundemo.py/cpp are working - https://github.com/mapnik/mapnik/issues/2324
