### ISSUE TITLE
Release FreeBSD checklist

### ISSUE THREAD

**Issue by pnorman** [mapnik/mapnik#2858]
A checklist to make sure Mapnik can be built on FreeBSD and updated in ports. Bolded are critical issues for being able to install from ports or using Mapnik documentation

* [x] **cc mapnik ports maintainer to this issue**
* [x] Use sh not bash (#2854)
* [x] Don't assume gcc/g++ (#2857, workaround exists)
* [ ] **Update [package list](https://github.com/mapnik/mapnik/wiki/FreeBSDInstallation)**
* [ ] Check `/usr/local/` for harfbuzz (#2869)
* [x] **Update configure list**
* [x] **Update compile lines**
* [ ] ~~test/visual/runner.cpp compilation with clang 3.6 (#2860)~~
* [x] image_filter.hpp compilation with clang 3.4 (#2859)
* [x] **mapnik-config hard-coded bash location (#2862)**
* [x] **missing `-lpthread` flag (#2861)**

**Comment by pnorman** [comment]
cc @illarionov

**Comment by pnorman** [comment]
Everything is good, except for the package list in the documentation is probably wrong.

**Comment by springmeyer** [comment]
thanks for leading this out. updating the package list can happen anytime now after release so closing this issue.
