### ISSUE TITLE
tests for geojson properties

### ISSUE THREAD

**Issue by mapsam** [mapnik/mapnik#3419]
At some point in the transfer to the `test-data` repo the newest version of the `escaped.geojson` fixture wasn't captured, which had extra property types (objects & arrays) to assert against. Currently there are not specific tests that assert properties from GeoJSON sources are captured, let's add them!  

### Tasks

- [x] update [`escaped.geojson`](https://raw.githubusercontent.com/mapnik/test-data/master/json/escaped.geojson) to include objects & arrays as values, https://github.com/mapnik/test-data/commit/c2515f594cc6b5a2c7758a31bce1e58a72e9e50f
- [x] add unit tests to `https://github.com/mapnik/mapnik/blob/master/test/unit/datasource/geojson.cpp` that assert property value types
- [x] write test that checks for lost spaces in object/array properties. This will currently fail, assuming the  [losing spaces](https://github.com/mapnik/node-mapnik/issues/642) is related to mapnik core.

### Refs

#2678 and https://github.com/mapnik/node-mapnik/issues/642

cc @springmeyer @artemp

**Comment by mapsam** [comment]
Looking at adding a new test. I'm not exactly sure how to iterate through the values provided by the mapnik datasource to match against a set of expected values.

Here's what I'm looking at:

```cpp
auto fields = ds->get_descriptor().get_descriptors();
std::initializer_list<std::string> names = {"Québec","[\"value1\",\"value 2\",3]","true","Test: \u005C","1.1","1","Test","{\"nested\":\"value with spaces\"}","this has spaces"};
REQUIRE_FIELD_NAMES(fields, names);
```

... but this results comparing key names vs values (i.e. `"double" == "1.1"`), which isn't what we want. Can I do something like `field.get_value()` in here somewhere? Something like:

```cpp
auto fields = ds->get_descriptor().get_descriptors();
std::initializer_list<std::string> names = {"Québec","[\"value1\",\"value 2\",3]","true","Test: \u005C","1.1","1","Test","{\"nested\":\"value with spaces\"}","this has spaces"};
auto itr_a = fields.begin();
auto const end_a = fields.end();
auto itr_b = names.begin();
for (; itr_a != end_a; ++itr_a, ++itr_b)
{
    CHECK(itr_a->get_value() == *itr_b);
}
```

cc @springmeyer @artemp

**Comment by artemp** [comment]
@mapsam - all is looking good after d19ff576dc853667997495e866afb282fac3ebcc
3909fe5b7dc46a3cf58259c17dbddbbf631aceff 
Could you test and close this issue, cheers.

**Comment by mapsam** [comment]
Tests work great @artemp - nice work!
